atcmd:
  name: Send AT Command
  description: Forward AT command to the device and execute it locally from MicroPython environment
  target:
    entity:
      domain: humidifier
  fields:
    cmd:
      description: AT command name
      required: true
      example: "FR"
      default: "FR"
      selector:
        text:
    data:
      description: Optional argument for the command
      required: false
      selector:
        text:
